swagger: '2.0'
info:
  title: Custom DP generator
  description: This is a REST API created with to generate custom display pictures to show affilition to brands and events.
  contact:
    email: maureen.ononiwu13@gmail.com
    url: https://www.linkedin.com/in/maureen-ononiwu/
  version: v1
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  Basic:
    type: basic
security:
  - Basic: []
paths:
  /make/dp/{slug}/:
    post:
      operationId: make_dp_create
      description: 'This end point creates the custom display pictures'
      parameters:
        - name: user_photo
          in: formData
          required: true
          type: file
      responses:
        '201':
          description: 'Successfully posted data to database'
          schema:
            $ref: '#/definitions/CustomDP_Model'
        '500':
          description: 'upload_photo field is required'
      consumes:
        - multipart/form-data
      tags:
        - This is where the magic happens!
    parameters:
      - name: slug
        in: path
        required: true
        type: string
  /campaign/{id}/:
    patch:
      operationId: update_modify
      description: 'Update/modify data about a campaign'
      parameters:
        - name: user_photo 
          in: formData
          required: false
          type: file
        - name: link
          in: formData
          required: false
          type: string
          format: slug
          pattern: ^[-a-zA-Z0-9_]+$
          maxLength: 250
          minLength: 1
        - name: height
          in: formData
          required: false
          type: integer
          maximum: 2147483647
          minimum: -2147483648
        - name: width
          in: formData
          required: false
          type: integer
          maximum: 2147483647
          minimum: -2147483648
        - name: position_x
          in: formData
          required: false
          type: integer
          maximum: 2147483647
          minimum: -2147483648
        - name: position_y
          in: formData
          required: false
          type: integer
          maximum: 2147483647
          minimum: -2147483648
        - name: border_radius
          in: formData
          required: false
          type: integer
          maximum: 2147483647
          minimum: -2147483648
          x-nullable: true
        - name: name
          in: formData
          required: false
          type: string
          maxLength: 200
          minLength: 1
        - name: description
          in: formData
          required: false
          type: string
          maxLength: 200
          minLength: 1
      responses:
        '200':
          description: 'Successful update'
          schema:
            $ref: '#/definitions/Campaign_Model'
        '500':
          description: 'Link already in use'
        '400':
          description: 'Invalid request, id does not exist'
      consumes:
        - multipart/form-data
      tags:
        - Modify campaign details
    parameters:
      - name: id
        in: path
        required: true
        type: string
    delete:
      operationId: modify_delete
      description: 'Delete campaign'
      parameters: []
      responses:
        '204':
          description: 'Successful deletion'
        '400':
          description: 'Invalid request, id does not exist'
      consumes:
        - multipart/form-data
      tags:
        - Delete campaign
  /campaign/:
    post:
      operationId: post_create
      description: 'This returns JSON data of the campaign'
      parameters:
        - name: banner
          in: formData
          required: true
          type: file
        - name: link
          in: formData
          required: true
          type: string
          format: slug
          pattern: ^[-a-zA-Z0-9_]+$
          maxLength: 250
          minLength: 1
        - name: height
          in: formData
          required: true
          type: integer
          maximum: 2147483647
          minimum: -2147483648
        - name: width
          in: formData
          required: true
          type: integer
          maximum: 2147483647
          minimum: -2147483648
        - name: position_x
          in: formData
          required: true
          type: integer
          maximum: 2147483647
          minimum: -2147483648
        - name: position_y
          in: formData
          required: true
          type: integer
          maximum: 2147483647
          minimum: -2147483648
        - name: border_radius
          in: formData
          required: false
          type: integer
          maximum: 2147483647
          minimum: -2147483648
          x-nullable: true
        - name: name
          in: formData
          required: true
          type: string
          maxLength: 200
          minLength: 1
        - name: description
          in: formData
          required: true
          type: string
          maxLength: 200
          minLength: 1
      responses:
        '201':
          description: 'successful request'
          schema:
            $ref: '#/definitions/Campaign_Model'
        '500':
          description: 'Missing field is required/link already in use'
      consumes:
        - multipart/form-data
      tags:
        - Create campaign
    parameters: []
  /{slug}/:
    get:
      operationId: read
      description: "This is the sharable link sent to people to create customised DPs using a campaign's banner"
      parameters: []
      responses:
        '200':
          description: 'Successful request'
        '500':
          description: 'Record does not exist'
      consumes:
        - multipart/form-data
      tags:
        - Sharable link given to users by campaign creators
    parameters:
      - name: slug
        in: path
        required: true
        type: string
definitions:
  CustomDP_Model:
    type: object
    properties:
      user_photo:
        title: user_photo
        type: string
        readOnly: true
        format: uri
        description: URL of the uploaded file 
  Campaign_Model:
    required:
      - link
      - height
      - width
      - position_x
      - position_y
      - name
      - description
    type: object
    properties:
      id:
        title: ID
        type: integer
        readOnly: true
        description: "This is the unique id of the camapaign"
        example: 1
      banner:
        title: banner
        type: string
        readOnly: true
        format: uri
        description: This is the URL of the uploaded banner for the campaign
        example: https://res.cloudinary/sample.png
      link:
        title: link
        type: string
        format: slug
        pattern: ^[-a-zA-Z0-9_]+$
        maxLength: 250
        minLength: 1
        description: This is the slug used to create the link used to create a sharable link.
        example: sluglink
      height:
        title: height
        type: integer
        maximum: 2147483647
        minimum: -2147483648
        description: This is the vertical length of the image to be pasted.
        example: 240
      width:
        title: width
        type: integer
        maximum: 2147483647
        minimum: -2147483648
        description: This is the horizontal length of the image to be pasted.
        example: 240
      position_x:
        title: Position x
        type: integer
        maximum: 2147483647
        minimum: -2147483648
        description: This is the distance of the image to be pasted on the banner from the left.
        example: 212
      position_y:
        title: Position y
        type: integer
        maximum: 2147483647
        minimum: -2147483648
        description: This is the distance of the image to be pasted on the banner from the top.
        example: 234
      border_radius:
        title: Border radius
        type: integer
        maximum: 2147483647
        minimum: -2147483648
        x-nullable: true
      name:
        title: name
        type: string
        maxLength: 200
        minLength: 1
        description: "This represents the name of the campaign."
        example: "Kwarabuild initiative"
      description:
        title: description
        type: string
        maxLength: 200
        minLength: 1
        description: The name of the campaign.
        example: Kwarabuild initiative
  # Campaign_update_Model:
  #     required:
  #       - link
  #       - height
  #       - width
  #       - position_x
  #       - position_y
  #       - name
  #       - description
  #     type: object
  #     properties:
  #       id:
  #         title: ID
  #         type: integer
  #         readOnly: true
  #         description: "This is the unique id of the camapaign"
  #         example: 1
  #       user_photo:
  #         title: user_photo
  #         type: string
  #         readOnly: true
  #         format: uri
  #         description: This is the URL of the uploaded banner for the campaign
  #         example: https://res.cloudinary/sample.png
  #       link:
  #         title: link
  #         type: string
  #         format: slug
  #         pattern: ^[-a-zA-Z0-9_]+$
  #         maxLength: 250
  #         minLength: 1
  #         description: This is the slug used to create the link used to create a sharable link.
  #         example: sluglink
  #       height:
  #         title: height
  #         type: integer
  #         maximum: 2147483647
  #         minimum: -2147483648
  #         description: This is the vertical length of the image to be pasted.
  #         example: 240
  #       width:
  #         title: width
  #         type: integer
  #         maximum: 2147483647
  #         minimum: -2147483648
  #         description: This is the horizontal length of the image to be pasted.
  #         example: 240
  #       position_x:
  #         title: Position x
  #         type: integer
  #         maximum: 2147483647
  #         minimum: -2147483648
  #         description: This is the distance of the image to be pasted on the banner from the left.
  #         example: 212
  #       position_y:
  #         title: Position y
  #         type: integer
  #         maximum: 2147483647
  #         minimum: -2147483648
  #         description: This is the distance of the image to be pasted on the banner from the top.
  #         example: 234
  #       border_radius:
  #         title: Border radius
  #         type: integer
  #         maximum: 2147483647
  #         minimum: -2147483648
  #         x-nullable: true
  #       name:
  #         title: name
  #         type: string
  #         maxLength: 200
  #         minLength: 1
  #         description: "This represents the name of the campaign."
  #         example: "Kwarabuild initiative"
  #       description:
  #         title: description
  #         type: string
  #         maxLength: 200
  #         minLength: 1
  #         description: The name of the campaign.
  #         example: Kwarabuild initiative




